//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raiduga.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raiduga.Web.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing news.
        /// </summary>
        public static string Admin_Home_ArticleDescription {
            get {
                return ResourceManager.GetString("Admin_Home_ArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contacts by affiliates.
        /// </summary>
        public static string Admin_Home_ContactDescription {
            get {
                return ResourceManager.GetString("Admin_Home_ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit content .
        /// </summary>
        public static string Admin_Home_ContentDescription {
            get {
                return ResourceManager.GetString("Admin_Home_ContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client feebacks.
        /// </summary>
        public static string Admin_Home_FeedbackDescription {
            get {
                return ResourceManager.GetString("Admin_Home_FeedbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View messages uses sent through &quot;Contact us&quot; form.
        /// </summary>
        public static string Admin_Home_MessageDescription {
            get {
                return ResourceManager.GetString("Admin_Home_MessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit service and theirs courses.
        /// </summary>
        public static string Admin_Home_ServiceDescription {
            get {
                return ResourceManager.GetString("Admin_Home_ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit slider which is in the header.
        /// </summary>
        public static string Admin_Home_SliderDescription {
            get {
                return ResourceManager.GetString("Admin_Home_SliderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string Admin_HomeTitle {
            get {
                return ResourceManager.GetString("Admin_HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Article_Author {
            get {
                return ResourceManager.GetString("Article_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles body.
        /// </summary>
        public static string Article_BodyHtml {
            get {
                return ResourceManager.GetString("Article_BodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Article_Description {
            get {
                return ResourceManager.GetString("Article_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is published?.
        /// </summary>
        public static string Article_IsPublished {
            get {
                return ResourceManager.GetString("Article_IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Article_Keywords {
            get {
                return ResourceManager.GetString("Article_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Article_Title {
            get {
                return ResourceManager.GetString("Article_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string Articles_Title {
            get {
                return ResourceManager.GetString("Articles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Articles_View {
            get {
                return ResourceManager.GetString("Articles_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Contacts_Address {
            get {
                return ResourceManager.GetString("Contacts_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours: from {0} to {1}.
        /// </summary>
        public static string Contacts_Hours {
            get {
                return ResourceManager.GetString("Contacts_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Contacts_Hours_From {
            get {
                return ResourceManager.GetString("Contacts_Hours_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours .
        /// </summary>
        public static string Contacts_Hours_Prompt {
            get {
                return ResourceManager.GetString("Contacts_Hours_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Contacts_Hours_To {
            get {
                return ResourceManager.GetString("Contacts_Hours_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Contacts_Latitude {
            get {
                return ResourceManager.GetString("Contacts_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Contacts_Longitude {
            get {
                return ResourceManager.GetString("Contacts_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts_Title {
            get {
                return ResourceManager.GetString("Contacts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear form.
        /// </summary>
        public static string ContactsForm_ClearForm {
            get {
                return ResourceManager.GetString("ContactsForm_ClearForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email *.
        /// </summary>
        public static string ContactsForm_Email {
            get {
                return ResourceManager.GetString("ContactsForm_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter you contact email *.
        /// </summary>
        public static string ContactsForm_Email_Placeholder {
            get {
                return ResourceManager.GetString("ContactsForm_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as read.
        /// </summary>
        public static string ContactsForm_MarkAsRead {
            get {
                return ResourceManager.GetString("ContactsForm_MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message *.
        /// </summary>
        public static string ContactsForm_Message {
            get {
                return ResourceManager.GetString("ContactsForm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message for me *.
        /// </summary>
        public static string ContactsForm_Message_Placeholder {
            get {
                return ResourceManager.GetString("ContactsForm_Message_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ContactsForm_MessageIsNew {
            get {
                return ResourceManager.GetString("ContactsForm_MessageIsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ContactsForm_Phone {
            get {
                return ResourceManager.GetString("ContactsForm_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your contact phone .
        /// </summary>
        public static string ContactsForm_Phone_Placeholder {
            get {
                return ResourceManager.GetString("ContactsForm_Phone_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone doesn&apos;t set.
        /// </summary>
        public static string ContactsForm_PhoneNotSet {
            get {
                return ResourceManager.GetString("ContactsForm_PhoneNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary office.
        /// </summary>
        public static string ContactsForm_Primary {
            get {
                return ResourceManager.GetString("ContactsForm_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * These fields are required..
        /// </summary>
        public static string ContactsForm_RequiredFieldsCaption {
            get {
                return ResourceManager.GetString("ContactsForm_RequiredFieldsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string ContactsForm_SendMessage {
            get {
                return ResourceManager.GetString("ContactsForm_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been successfully sent!.
        /// </summary>
        public static string ContactsForm_SuccessfullySent {
            get {
                return ResourceManager.GetString("ContactsForm_SuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts form.
        /// </summary>
        public static string ContactsForm_Title {
            get {
                return ResourceManager.GetString("ContactsForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content_BodyHtml {
            get {
                return ResourceManager.GetString("Content_BodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (is a key value).
        /// </summary>
        public static string Content_Name {
            get {
                return ResourceManager.GetString("Content_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html contents.
        /// </summary>
        public static string Content_Title {
            get {
                return ResourceManager.GetString("Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html body.
        /// </summary>
        public static string Course_BodyHtml {
            get {
                return ResourceManager.GetString("Course_BodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course will be deleted. Do you really want to delete it?.
        /// </summary>
        public static string Course_DeletePrompt {
            get {
                return ResourceManager.GetString("Course_DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string Course_Description {
            get {
                return ResourceManager.GetString("Course_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course duration.
        /// </summary>
        public static string Course_Duration {
            get {
                return ResourceManager.GetString("Course_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Course_Name {
            get {
                return ResourceManager.GetString("Course_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Course_Price {
            get {
                return ResourceManager.GetString("Course_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new item.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our features.
        /// </summary>
        public static string Features_Title {
            get {
                return ResourceManager.GetString("Features_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art and intelectual grows center.
        /// </summary>
        public static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Home_ContactsUsPrompt {
            get {
                return ResourceManager.GetString("Home_ContactsUsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast contacts.
        /// </summary>
        public static string Home_FastContacts_Title {
            get {
                return ResourceManager.GetString("Home_FastContacts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image_Caption {
            get {
                return ResourceManager.GetString("Image_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string Login_HeadingPrompt {
            get {
                return ResourceManager.GetString("Login_HeadingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Login_Hello {
            get {
                return ResourceManager.GetString("Login_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Login_LogOff {
            get {
                return ResourceManager.GetString("Login_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new user.
        /// </summary>
        public static string Login_RegisterNew {
            get {
                return ResourceManager.GetString("Login_RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages_Title {
            get {
                return ResourceManager.GetString("Messages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Courses.
        /// </summary>
        public static string Service_AllCourses {
            get {
                return ResourceManager.GetString("Service_AllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Service_Details {
            get {
                return ResourceManager.GetString("Service_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Service_Title {
            get {
                return ResourceManager.GetString("Service_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiduga.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Slider_BackToList {
            get {
                return ResourceManager.GetString("Slider_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Slider_Cancel {
            get {
                return ResourceManager.GetString("Slider_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new slide.
        /// </summary>
        public static string Slider_CreateNewSlide {
            get {
                return ResourceManager.GetString("Slider_CreateNewSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Slider_Delete {
            get {
                return ResourceManager.GetString("Slider_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slide item will be deleted. Do you really want to delete it?.
        /// </summary>
        public static string Slider_DeletePrompt {
            get {
                return ResourceManager.GetString("Slider_DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        public static string Slider_DeleteTitle {
            get {
                return ResourceManager.GetString("Slider_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Slider_Edit {
            get {
                return ResourceManager.GetString("Slider_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide picture.
        /// </summary>
        public static string Slider_Image {
            get {
                return ResourceManager.GetString("Slider_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider item.
        /// </summary>
        public static string Slider_Name {
            get {
                return ResourceManager.GetString("Slider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string Slider_Page_Title {
            get {
                return ResourceManager.GetString("Slider_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Slider_Save {
            get {
                return ResourceManager.GetString("Slider_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another image.
        /// </summary>
        public static string Slider_SelectAnotherImage {
            get {
                return ResourceManager.GetString("Slider_SelectAnotherImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Sub title.
        /// </summary>
        public static string Slider_SubTitle {
            get {
                return ResourceManager.GetString("Slider_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Title.
        /// </summary>
        public static string Slider_Title {
            get {
                return ResourceManager.GetString("Slider_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feedback will be deleted. Do you really want to delete it?.
        /// </summary>
        public static string UserFeedback_DeletePrompt {
            get {
                return ResourceManager.GetString("UserFeedback_DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is feedback is active.
        /// </summary>
        public static string UserFeedback_IsActive {
            get {
                return ResourceManager.GetString("UserFeedback_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks text.
        /// </summary>
        public static string UserFeedback_Text {
            get {
                return ResourceManager.GetString("UserFeedback_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks.
        /// </summary>
        public static string UserFeedback_Title {
            get {
                return ResourceManager.GetString("UserFeedback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserFeedback_UserName {
            get {
                return ResourceManager.GetString("UserFeedback_UserName", resourceCulture);
            }
        }
    }
}
