//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raiduga.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raiduga.Web.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Slider_BackToList {
            get {
                return ResourceManager.GetString("Slider_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Slider_Cancel {
            get {
                return ResourceManager.GetString("Slider_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new slide.
        /// </summary>
        public static string Slider_CreateNewSlide {
            get {
                return ResourceManager.GetString("Slider_CreateNewSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Slider_Delete {
            get {
                return ResourceManager.GetString("Slider_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slide item will be deleted. Are you realy want to delete it?.
        /// </summary>
        public static string Slider_DeletePrompt {
            get {
                return ResourceManager.GetString("Slider_DeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        public static string Slider_DeleteTitle {
            get {
                return ResourceManager.GetString("Slider_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Slider_Edit {
            get {
                return ResourceManager.GetString("Slider_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide picture.
        /// </summary>
        public static string Slider_Image {
            get {
                return ResourceManager.GetString("Slider_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider item.
        /// </summary>
        public static string Slider_Name {
            get {
                return ResourceManager.GetString("Slider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Slider_Save {
            get {
                return ResourceManager.GetString("Slider_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another image.
        /// </summary>
        public static string Slider_SelectAnotherImage {
            get {
                return ResourceManager.GetString("Slider_SelectAnotherImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Sub title.
        /// </summary>
        public static string Slider_SubTitle {
            get {
                return ResourceManager.GetString("Slider_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Title.
        /// </summary>
        public static string Slider_Title {
            get {
                return ResourceManager.GetString("Slider_Title", resourceCulture);
            }
        }
    }
}
