// <auto-generated />
namespace Raiduga.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AffiliateSimpleContactsSolution : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AffiliateSimpleContactsSolution));
        
        string IMigrationMetadata.Id
        {
            get { return "201701111535376_AffiliateSimpleContactsSolution"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
